const PDFDocument = require("pdfkit");

const generateTicketPDF = (ticketData) => {

    return new Promise((resolve, reject) => {

        const doc = new PDFDocument({
            size: "A4",
            margin: 50
        });

        const buffers = [];

        doc.on("data", buffers.push.bind(buffers));

        doc.on("end", () => {
            resolve(Buffer.concat(buffers));
        });

        doc.on("error", reject);

        //---------------------------------
        // HEADER
        //---------------------------------

        doc
            .fontSize(22)
            .text("Horizon Elite Airways", {
                align: "center"
            });

        doc.moveDown();

        doc
            .fontSize(18)
            .text("Electronic Ticket", {
                align: "center"
            });

        doc.moveDown(2);

        //---------------------------------
        // Passenger
        //---------------------------------

        doc.fontSize(14).text("Passenger Information");

        doc.moveDown(0.5);

        doc.fontSize(11);

        doc.text(`Name : ${ticketData.passenger_name}`);

        doc.text(`Passport : ${ticketData.passport_number || "-"}`);

        doc.text(`Email : ${ticketData.email}`);

        doc.moveDown();

        //---------------------------------
        // Booking
        //---------------------------------

        doc.fontSize(14).text("Booking Information");

        doc.moveDown(0.5);

        doc.fontSize(11);

        doc.text(`PNR : ${ticketData.pnr}`);

        doc.text(`Ticket Number : ${ticketData.ticket_number || "Not Ticketed"}`);

        doc.text(`Booking Status : ${ticketData.booking_status}`);

        doc.text(`Ticket Status : ${ticketData.ticketing_status}`);

        doc.moveDown();

        //---------------------------------
        // Flight
        //---------------------------------

        doc.fontSize(14).text("Flight Information");

        doc.moveDown(0.5);

        doc.fontSize(11);

        doc.text(`Airline : ${ticketData.airline}`);

        doc.text(`Flight Number : ${ticketData.flight_number}`);

        doc.text(`Route : ${ticketData.origin} → ${ticketData.destination}`);

        doc.text(`Departure : ${ticketData.departure}`);

        doc.text(`Arrival : ${ticketData.arrival}`);

        doc.moveDown();

        //---------------------------------
        // Payment
        //---------------------------------

        doc.fontSize(14).text("Payment");

        doc.moveDown(0.5);

        doc.fontSize(11);

        doc.text(`Amount : ${ticketData.amount} ${ticketData.currency}`);

        doc.moveDown(2);

        //---------------------------------
        // QR Placeholder
        //---------------------------------

        doc.rect(220, 620, 120, 120).stroke();

        doc.text(
            "QR CODE",
            250,
            675
        );

        doc.moveDown(7);

        //---------------------------------
        // Footer
        //---------------------------------

        doc.fontSize(10);

        doc.text(
            "This electronic ticket was generated by Horizon Elite Booking System.",
            {
                align: "center"
            }
        );

        doc.end();

    });

};

module.exports = generateTicketPDF;